name: Build and push to DO

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t registry.digitalocean.com/rhemz/k8s-images:tg-plex-bot-latest
      
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600
      
    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/rhemz/k8s-images:tg-plex-bot-latest

    - name: Get temporary DO kubeconfig
      run: doctl kubernetes cluster kubeconfig save ${{ secrets.DO_K8S_CLUSTER }} --expiry-seconds 600

    - name: Bounce the deployment
      run: kubectl -n telegram rollout restart deploy/plex-bot
