name: Build and push to DO

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # DOCR free plan, only 1 repo so everything is tags and -latest :(
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ${{ secrets.DOCR_TAG }}-latest
      
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
    - name: Log in to DOCR
      run: doctl registry login --expiry-seconds 300
      
    - name: Push image to DigitalOcean Container Registry
      run: docker push ${{ secrets.DOCR_TAG }}-latest

    - name: Get temporary DO kubeconfig
      run: doctl kubernetes cluster kubeconfig save ${{ secrets.DO_K8S_CLUSTER }} --expiry-seconds 60

    - name: Bounce the deployment
      run: kubectl -n telegram rollout restart deploy/plex-bot
